print("===== Student Profile =====")

name = input("Enter student name: ")
age = int(input("Enter age: "))
course = input("Enter course: ")
college = input("Enter college name: ")
email = input("Enter email: ")
phone = input("Enter phone number: ")

print("\n===== Student Profile =====")
print(name)
print( age)
print( course)
print( college)
print( email)
print( phone)
